#!/usr/bin/env bash
#
# Copyright 2017 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# JMX settings. Remote JMX without authentication allows remote code execution,
# so it is off by default; set KSQL_JMX_OPTS to enable it. Must be exported --
# ksql-run-class applies its own unrestricted default if KSQL_JMX_OPTS is empty.
# jmxremote.host is what confines the listener; local.only does not.
KSQL_JMX_OPTS_FROM_OPERATOR="${KSQL_JMX_OPTS-}"
if [ -z "$KSQL_JMX_OPTS_FROM_OPERATOR" ]; then
  export KSQL_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.host=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
fi

# Ensure that KSQL picks up the correct log4j properties file
if [ -z "$KSQL_LOG4J_OPTS" ]; then
  export KSQL_LOG4J_OPTS="-Dlog4j.configuration=file:/etc/${COMPONENT}/log4j.properties"
fi

# The JMX client needs to be able to connect to java.rmi.server.hostname.
# The default for bridged network is the bridged IP so you will only be able to connect from another docker container.
# For host network, this is the IP that the hostname on the host resolves to.

# If you have more that one network configured, hostname -i gives you all the IPs,
# the default is to pick the first IP (or network).
export KSQL_JMX_HOSTNAME=${KSQL_JMX_HOSTNAME:-$(hostname -i | cut -d" " -f1)}

# JMX port to use. ksql-run-class appends the port to whichever KSQL_JMX_OPTS is
# in effect, so setting JMX_PORT is sufficient here.
if [ -n "${KSQL_JMX_PORT-}" ]; then
  export JMX_PORT=$KSQL_JMX_PORT

  if [ -z "$KSQL_JMX_OPTS_FROM_OPERATOR" ]; then
    echo "WARNING: KSQL_JMX_PORT is set without KSQL_JMX_OPTS. JMX will listen on loopback only."
    echo "WARNING: To enable remote JMX, set KSQL_JMX_OPTS with authentication and TLS. See"
    echo "WARNING: https://docs.confluent.io/platform/current/ksqldb/operate-and-deploy/monitoring.html"
  elif [[ $KSQL_JMX_OPTS != *"java.rmi.server.hostname"* && -n "$KSQL_JMX_HOSTNAME" ]]; then
    # Supply the RMI hostname the operator cannot know at image-build time.
    export KSQL_JMX_OPTS="$KSQL_JMX_OPTS -Djava.rmi.server.hostname=$KSQL_JMX_HOSTNAME"
  fi
fi

echo "===> Launching ${COMPONENT} ... "
exec ksql-server-start /etc/"${COMPONENT}"/"${COMPONENT}".properties
