name: ksql-images
lang: python
lang_version: 3.8
git:
  enable: true
code_artifact:
  enable: true
  package_paths:
    - maven-snapshots/maven/io.confluent.ksql/ksql-images-parent
semaphore: 
  enable: true
  pipeline_type: cp-dockerfile
  execution_time_limit: {"hours": 8}
  docker_repos: [
    'confluentinc/cp-ksqldb-server',
    'confluentinc/cp-ksqldb-cli',
    'confluentinc/ksqldb-examples'
  ]
  maven_phase: 'package integration-test'
  maven_skip_deploy: true
  build_arm: true
  nano_version: true
  os_types: ["ubi8"]
  pip_install_package: 'tox==3.28.0'
  use_packages: true
  cp_images: true
  sign_images: true
  push_latest: true
  tasks:
    - name: cp-dockerfile-build
      branch: "master"
      pipeline_file: .semaphore/cp_dockerfile_build.yml
      parameters:
        - name: CONFLUENT_VERSION
          required: true
        - name: PACKAGES_URL
          required: true
        - name: PACKAGES_MAVEN_URL
          required: true
        - name: PACKAGING_BUILD_NUMBER
          required: true
        - name: ALLOW_UNSIGNED
          required: true
          default_value: 'False'
          options:
            - 'True'
            - 'False'
        - name: CONFLUENT_DEB_VERSION
          required: true
          default_value: '1'
    - name: cp-dockerfile-promote
      branch: master
      pipeline_file: .semaphore/cp_dockerfile_promote.yml
      parameters:
        - name: CONFLUENT_VERSION
          required: true
        - name: IMAGE_REVISION
          required: true
          default_value: '1'
        - name: UPDATE_LATEST_TAG
          required: true
        - name: PACKAGING_BUILD_NUMBER
          required: true
        - name: PROMOTE_OS_TYPE
          required: true
          options:
            - 'deb'
            - 'ubi'
