#!/usr/bin/env bash
#
# Copyright 2025 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script runs KSQL in CLI mode
export COMPONENT=ksqldb-cli

. /etc/confluent/docker/bash-config

echo "===> User"
id

echo "===> Configuring KSQL CLI..."
/etc/confluent/docker/cli/configure

# Set log4j options for CLI
export KSQL_LOG4J_OPTS="-Dlog4j2.configurationFile=file:/etc/${COMPONENT}/log4j2.yaml"

# If no arguments provided, default to localhost:8088
if [ $# -eq 0 ]; then
  echo "===> Connecting to KSQL Server at http://localhost:8088"
  exec ksql "http://localhost:8088"
else
  echo "===> Starting KSQL CLI with provided arguments"
  exec ksql "$@"
fi