#!/usr/bin/env bash
#
# Copyright 2017 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# JMX settings.
# This image does not enable remote JMX for you. Remote JMX without
# authentication is a code-execution primitive for any peer that can reach the
# port, so when KSQL_JMX_OPTS is unset, ksql-run-class applies its loopback-only
# default. Operators who need remote JMX set KSQL_JMX_OPTS explicitly, with
# authentication and TLS. See:
# https://docs.confluent.io/platform/current/ksqldb/operate-and-deploy/monitoring.html

# Ensure that KSQL picks up the correct log4j properties file
if [ -z "$KSQL_LOG4J_OPTS" ]; then
  export KSQL_LOG4J_OPTS="-Dlog4j2.configurationFile=file:/etc/${COMPONENT}/log4j2.yaml"
fi

# The JMX client needs to be able to connect to java.rmi.server.hostname.
# The default for bridged network is the bridged IP so you will only be able to connect from another docker container.
# For host network, this is the IP that the hostname on the host resolves to.

# If you have more that one network configured, hostname -i gives you all the IPs,
# the default is to pick the first IP (or network).
export KSQL_JMX_HOSTNAME=${KSQL_JMX_HOSTNAME:-$(hostname -i | cut -d" " -f1)}

# JMX port to use
if [ -n "${KSQL_JMX_PORT-}" ]; then
  export JMX_PORT=$KSQL_JMX_PORT

  if [ -z "${KSQL_JMX_OPTS-}" ]; then
    echo "===> WARNING: KSQL_JMX_PORT is set but KSQL_JMX_OPTS is not."
    echo "===> WARNING: ksqlDB will bind JMX with loopback-only defaults and will NOT accept remote connections."
    echo "===> WARNING: To enable remote JMX, set KSQL_JMX_OPTS explicitly with authentication and TLS. See:"
    echo "===> WARNING: https://docs.confluent.io/platform/current/ksqldb/operate-and-deploy/monitoring.html"
  elif [[ $KSQL_JMX_OPTS != *"java.rmi.server.hostname"* && -n "$KSQL_JMX_HOSTNAME" ]]; then
    # The JMX client needs to reach java.rmi.server.hostname, which the operator
    # is unlikely to know at image-build time, so supply it if they have not.
    export KSQL_JMX_OPTS="$KSQL_JMX_OPTS -Djava.rmi.server.hostname=$KSQL_JMX_HOSTNAME"
  fi
fi

echo "===> Launching ${COMPONENT} ... "
exec ksql-server-start /etc/"${COMPONENT}"/"${COMPONENT}".properties
